### ISSUE TITLE
Just wanted to check if this is the active project for micropsi 2 . 

### ISSUE THREAD

**Issue by learnnshare** [joschabach/micropsi2#99]
Just wanted to check if this is the active project for micropsi 2 .  I dont see any code changes since 5 years, so just wanted to check.

**Comment by BucketoHurt** [comment]
Hi @learnnshare  and @joschabach , I would also really like to know if this is still the active project. I am really interested in working on this project as a hobby (for now). 
Any advise on where to get started would be much appreciated.
Thanks in advance
Regards
Mark

**Comment by learnnshare** [comment]
Dear Mark,
I was looking for details about this project - myself.
Background:
I was baffled about the term "Affect" ( since there were multiple definitions in literature ). I wanted a comprehensive understanding, and that was when I stumbled on Lex Friedman's conversation with Joscha on this topic.
I heard Joschas' excellent description related to emotions and Affect on Lex Podcast.
I had prepared mind-map linking ideas and wanted to dive deeper ( Attached ).
I wanted to work on this project ( with community support)
Bach, J. (2012). Modeling Motivation and the Emergence of Affect in a Cognitive Agent. In Wang, P. (ed). ( attached)
http://bach.ai/publications/
If you do come across any details about this progress, or you happen to install this program, please let me know.
Thanks
Amar

**Comment by vidaurre** [comment]
Hi,
I also find this project really interesting, and I was also considering to dive a bit into it —so I was wondering if you guys found something in the end about whether or not this is an active project?
Many thanks
Diego

**Comment by vidaurre** [comment]
Hi,
I also find this project really interesting, and I was also considering to dive a bit into it —so I was wondering if you guys found something in the end about whether or not this is an active project?
Many thanks
Diego

**Comment by learnnshare** [comment]
Hello Diego,
I am also looking for someone who has worked on it.
If you find any, please let me know.
Thanks

**Comment by Tesseract19** [comment]
...?

**Comment by jonasrk** [comment]
I haven't been involved in a few years but I'm reasonably confident that this project has not been under active development for a few years now. @spalanzani @policecar @Doik @joschabach would need to confirm though.

**Comment by joschabach** [comment]
Yes, the project has not been updated in a few years.

Am Fr., 17. Sept. 2021 um 02:53 Uhr schrieb Jonas Kemper <
***@***.***>:
